import React, { useState, useEffect } from 'react';
import { api } from '../lib/api.js';

function FeedCard({ entry }) {
  const [expanded, setExpanded] = useState(false);

  // Format feed_date nicely
  const displayDate = (() => {
    try {
      const d = new Date(entry.feed_date + 'T12:00:00');
      return d.toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });
    } catch {
      return entry.feed_date;
    }
  })();

  // Parse content: split on --- separators for sections
  const sections = entry.content
    .split(/\n---+\n/)
    .map(s => s.trim())
    .filter(Boolean);

  return (
    <div className="bg-white rounded-2xl border border-gray-200 overflow-hidden shadow-sm hover:shadow-md transition-shadow">
      {/* Card header */}
      <div className="px-5 py-4 border-b border-gray-100 flex items-start justify-between gap-4">
        <div className="flex-1 min-w-0">
          <p className="text-xs font-semibold text-[#0066FF] uppercase tracking-wide mb-1">
            📋 Daily Regulatory Intelligence
          </p>
          <p className="font-bold text-gray-900 text-sm leading-tight">{entry.title || displayDate}</p>
          <p className="text-xs text-gray-400 mt-0.5">{displayDate}</p>
        </div>
        {entry.summary && (
          <div className="flex-shrink-0 px-3 py-1 rounded-full text-xs font-medium bg-[#EFF6FF] text-[#0066FF] border border-[#BFDBFE] max-w-[200px] line-clamp-2">
            {entry.summary}
          </div>
        )}
      </div>

      {/* Content */}
      <div className="px-5 py-4">
        {sections.length > 0 ? (
          <>
            {/* Show first section always */}
            <div className="text-sm text-gray-700 whitespace-pre-wrap font-mono leading-relaxed bg-gray-50 rounded-xl p-3 text-xs">
              {sections[0]}
            </div>

            {sections.length > 1 && (
              <>
                {expanded && sections.slice(1).map((section, i) => (
                  <div key={i} className="mt-3 text-sm text-gray-700 whitespace-pre-wrap font-mono leading-relaxed bg-gray-50 rounded-xl p-3 text-xs">
                    {section}
                  </div>
                ))}
                <button
                  onClick={() => setExpanded(!expanded)}
                  className="mt-3 text-xs font-semibold text-[#0066FF] hover:underline flex items-center gap-1"
                >
                  {expanded ? '▲ Show less' : `▼ Show all ${sections.length} sections`}
                </button>
              </>
            )}
          </>
        ) : (
          <pre className="text-xs text-gray-700 whitespace-pre-wrap font-mono leading-relaxed bg-gray-50 rounded-xl p-3">
            {entry.content}
          </pre>
        )}
      </div>

      <div className="px-5 py-2 bg-gray-50 border-t border-gray-100 text-xs text-gray-400">
        Posted by {entry.posted_by || 'sophia'} · {entry.created_at?.slice(0, 16).replace('T', ' ')} UTC
      </div>
    </div>
  );
}

export default function RegulatoryIntel() {
  const [entries, setEntries] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    api.get('/api/regulatory-feed')
      .then(data => {
        setEntries(data.entries || []);
        setLoading(false);
      })
      .catch(err => {
        setError(err.message || 'Failed to load feed');
        setLoading(false);
      });
  }, []);

  return (
    <div className="max-w-3xl mx-auto px-6 py-8">
      {/* Header */}
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-gray-900 flex items-center gap-2">
          🌐 Regulatory Intelligence
        </h1>
        <p className="text-gray-500 text-sm mt-1">
          Daily briefings from OFAC, FinCEN, and FATF — generated by Sophia each morning.
        </p>
      </div>

      {/* Status bar */}
      <div className="mb-5 flex items-center gap-2 text-xs text-gray-500">
        <span className="w-2 h-2 rounded-full bg-green-400 inline-block"></span>
        Live feed · {entries.length} brief{entries.length !== 1 ? 's' : ''} available
        <span className="ml-auto text-gray-400">Sources: OFAC SDN · FinCEN · FATF</span>
      </div>

      {/* Content */}
      {loading && (
        <div className="text-center py-16 text-gray-500">
          <div className="text-4xl mb-3">📡</div>
          <p className="text-sm">Loading intelligence feed…</p>
        </div>
      )}

      {error && (
        <div className="bg-red-50 border border-red-200 rounded-xl p-4 text-sm text-red-600">
          ⚠️ {error}
        </div>
      )}

      {!loading && !error && entries.length === 0 && (
        <div className="text-center py-16 text-gray-500">
          <div className="text-5xl mb-4">📭</div>
          <p className="font-semibold text-gray-700">No entries yet</p>
          <p className="text-sm text-gray-400 mt-1">Sophia posts a new brief each morning. Check back after the next run.</p>
        </div>
      )}

      {!loading && !error && entries.length > 0 && (
        <div className="space-y-4">
          {entries.map(entry => (
            <FeedCard key={entry.id} entry={entry} />
          ))}
        </div>
      )}
    </div>
  );
}
