// ============================================================
// VIGÍA BSA DECISION ENGINE — BUILD HEADER
// ============================================================
// Tool Name:        VIGÍA Compliance Portal — Employee Whitelist
// Build Date:       2026-05-14
// Authorized by:    Zaid Khan (U087TL6CGNM)
// POLICY COMPLIANCE: POL-BSA-001-v4.2
// EWRA RISK MITIGATION: Risk ID(s): EWRA-01 | Residual: LOW
// ============================================================

const EMPLOYEES = {
  'aadarsh.singh@airtm.io': { name: 'Aadarsh Kumar Singh', department: 'Marketplace', title: 'Head of Analytics', role: 'SUPPORT_ANALYST' },
  'aashi.choudhary@airtm.io': { name: 'Aashi Choudhary', department: 'Compliance', title: 'AML Junior Analyst', role: 'KYC_ANALYST' },
  'abraham.lopez@airtm.io': { name: 'Abraham Martínez López', department: 'Marketplace', title: 'Data Scientist', role: 'SUPPORT_ANALYST' },
  'adalberto.zapata@airtm.io': { name: 'Adalberto Benitiz Zapata', department: 'Growth & Mktg', title: 'Sr Growth Lead', role: 'SUPPORT_ANALYST' },
  'adam.baer@airtm.io': { name: 'Adam Baer', department: 'Finance', title: 'VP Financial Controller', role: 'LEADERSHIP' },
  'aimee.barajas@airtm.io': { name: 'Aimee Vanessa Villarroel Barajas', department: 'Compliance', title: 'Compliance 1st level Analyst', role: 'KYC_ANALYST' },
  'alan.tormente@airtm.io': { name: 'Alan Lucian Milanes Tormente', department: 'Tech', title: 'Senior Software Engineer (Backend)', role: 'SUPPORT_ANALYST' },
  'alberto.dubovoy@airtm.io': { name: 'Alberto Pickering Dubovoy', department: 'Tech', title: 'Tech Lead', role: 'SUPPORT_ANALYST' },
  'aldo.minutti@airtm.io': { name: 'Aldo Funes Minutti', department: 'Tech', title: 'VP of Engineering', role: 'LEADERSHIP' },
  'alexis.vicente@airtm.io': { name: 'Alexis Mishell Rodriguez Vicente', department: 'CommOps', title: 'Subject Matter Expert', role: 'SUPPORT_ANALYST' },
  'ali.areski@airtm.io': { name: 'Ali Areski', department: 'Compliance', title: 'Governance and Controls Analyst', role: 'KYC_ANALYST' },
  'allan.silva@airtm.io': { name: 'Allan Raul Silva', department: 'Product', title: 'Senior Product Manager', role: 'SUPPORT_ANALYST' },
  'anahita.arora@airtm.io': { name: 'Anahita Arora', department: 'Finance', title: 'CFO', role: 'LEADERSHIP' },
  'ana.marquez@airtm.io': { name: 'Ana Isabel Villarroel Marquez', department: 'Compliance', title: 'Verification Analyst', role: 'KYC_ANALYST' },
  'andres.monroy@airtm.io': { name: 'Andres Alberto Huerta Monroy', department: 'Compliance', title: 'Verification Analyst', role: 'KYC_ANALYST' },
  'angy.tovar@airtm.io': { name: 'Angy Mileidy Duarte de Tovar', department: 'CommOps', title: 'CommOps Manager', role: 'SUPPORT_ANALYST' },
  'anny.castro@airtm.io': { name: 'Anny Marleidy Duarte Castro', department: 'Growth & Mktg', title: 'Social Media Support & Community Voice', role: 'SUPPORT_ANALYST' },
  'anyelina.martinez@airtm.io': { name: 'Anyelina Estrella Martinez', department: 'Compliance', title: 'Compliance 1st level Analyst', role: 'KYC_ANALYST' },
  'arshi.singh@airtm.io': { name: 'Arshi Singh', department: 'Product', title: 'CPO', role: 'LEADERSHIP' },
  'arturo.perdomo@airtm.io': { name: 'Arturo Ernesto Perdomo', department: 'Compliance', title: 'Verification Analyst', role: 'KYC_ANALYST' },
  'ashvini.weragoda@airtm.io': { name: 'Ashvini Weragoda', department: 'CommOps', title: 'Support Agent', role: 'SUPPORT_ANALYST' },
  'bruno.picciafuoco@airtm.io': { name: 'Bruno Dos Santos Picciafuoco', department: 'Tech', title: 'Senior Software Engineer (Backend)', role: 'SUPPORT_ANALYST' },
  'bryan.florez@airtm.io': { name: 'Bryan Andres Medina Florez', department: 'CommOps', title: 'Support Agent', role: 'SUPPORT_ANALYST' },
  'camila.arce@airtm.io': { name: 'Camila María Mercado Arce', department: 'CommOps', title: 'Support Agent', role: 'SUPPORT_ANALYST' },
  'camilo.chaparro@airtm.io': { name: 'Camilo Esteban Cardozo Chaparro', department: 'People', title: 'Recruiter', role: 'SUPPORT_ANALYST' },
  'carlos.miranda@airtm.io': { name: 'Carlos Habib De Lamadrid Miranda', department: 'Legal', title: 'Counsel', role: 'SUPPORT_ANALYST' },
  'carlos.flores@airtm.io': { name: 'Carlos Roberto Hernández Flores', department: 'CommOps', title: 'Support Agent', role: 'SUPPORT_ANALYST' },
  'christian.colla@airtm.io': { name: 'Christian Ariel Colla', department: 'Finance', title: 'Senior Accountant', role: 'SUPPORT_ANALYST' },
  'christian.cabello@airtm.io': { name: 'Christian Esteban Canahuire Cabello', department: 'Tech', title: 'Senior Software Engineer (Android)', role: 'SUPPORT_ANALYST' },
  'cicero.camargo@airtm.io': { name: 'Cicero Augusto De Souza Camargo', department: 'Tech', title: 'Senior Software Engineer (iOS)', role: 'SUPPORT_ANALYST' },
  'claudia.merino@airtm.io': { name: 'Claudia Erika Martinez Merino', department: 'Compliance', title: 'KYC Global Manager', role: 'KYC_ANALYST' },
  'cristina.jordan@airtm.io': { name: 'Cristina Rodriguez Jordan', department: 'Growth & Mktg', title: 'Marketing Operations Coordinator', role: 'SUPPORT_ANALYST' },
  'cristobal.ortega@airtm.io': { name: 'Cristobal Galguera Ortega', department: 'Product', title: 'Senior Product Manager', role: 'SUPPORT_ANALYST' },
  'dang.tran@airtm.io': { name: 'Dang Hoang Vu Tran', department: 'CommOps', title: 'Support Agent', role: 'SUPPORT_ANALYST' },
  'daniela.carvajal@airtm.io': { name: 'Daniela Sarai Perez Carvajal', department: 'Growth & Mktg', title: 'Growth Marketing Associate Analyst', role: 'SUPPORT_ANALYST' },
  'daniel.marroquin@airtm.io': { name: 'Daniel Benjamin Almaraz Marroquín', department: 'Compliance', title: '1st Level Compliance Lead', role: 'TM_ANALYST' },
  'daniel.villegas@airtm.io': { name: 'Daniel Enrique De La Cruz Villegas', department: 'Marketplace', title: 'Marketplace Ops Associate', role: 'SUPPORT_ANALYST' },
  'daniel.quintero@airtm.io': { name: 'Daniel Quintero', department: 'Finance', title: 'Senior Accountant', role: 'SUPPORT_ANALYST' },
  'diego.pels@airtm.io': { name: 'Diego Alan Pels', department: 'Sales', title: 'Account Manager', role: 'SUPPORT_ANALYST' },
  'edgar.hirama@airtm.io': { name: 'Edgar Hirama', department: 'Tech', title: 'Senior Software Engineer (iOS)', role: 'SUPPORT_ANALYST' },
  'edoe.rodriguez@airtm.io': { name: 'Edoe Jose Chourio Rodriguez', department: 'CommOps', title: 'Senior Support Agent', role: 'SUPPORT_ANALYST' },
  'eduardo.perez@airtm.io': { name: 'Eduardo Jose Nieto Perez', department: 'Compliance', title: 'Fraud Analyst', role: 'FRAUD_INVESTIGATOR' },
  'eduardo.ramirez@airtm.io': { name: 'Eduardo Mariano de Udaeta Ramírez', department: 'CommOps', title: 'Support Agent', role: 'SUPPORT_ANALYST' },
  'eleana.rodriguez@airtm.io': { name: 'Eleana Judith Chourio Rodriguez', department: 'Compliance', title: 'Compliance 1st level Analyst', role: 'KYC_ANALYST' },
  'elias.duarte@airtm.io': { name: 'Elías David Duarte', department: 'Tech', title: 'Software Engineer (Backend)', role: 'SUPPORT_ANALYST' },
  'enrique.lopez@airtm.io': { name: 'Enrique Jose Santeliz Lopez', department: 'Tech', title: 'Senior Software Engineer (Backend)', role: 'SUPPORT_ANALYST' },
  'erick.romero@airtm.io': { name: 'Erick Cedillo Romero', department: 'Tech', title: 'Software Engineer (Frontend)', role: 'SUPPORT_ANALYST' },
  'estefania.fucci@airtm.io': { name: 'Estefania Celeste Baleiron fucci', department: 'Compliance', title: 'KYC Analyst', role: 'KYC_ANALYST' },
  'fabio.sejas@airtm.io': { name: 'Fabio Marcelo Alcocer Sejas', department: 'CommOps', title: 'Support Agent', role: 'SUPPORT_ANALYST' },
  'florencia.tisocco@airtm.io': { name: 'Florencia Agustina Tisocco', department: 'Growth & Mktg', title: 'Senior Engagement Analyst', role: 'SUPPORT_ANALYST' },
  'florencia.carnelutto@airtm.io': { name: 'Florencia Carnelutto', department: 'Finance', title: 'Data Scientist', role: 'SUPPORT_ANALYST' },
  'francisco.valdez@airtm.io': { name: 'Francisco Elias Valdez', department: 'Product', title: 'Senior UX Designer', role: 'SUPPORT_ANALYST' },
  'gabriel.silva@airtm.io': { name: 'Gabriel Guilherme de Oliveira Silva', department: 'CommOps', title: 'Support Agent', role: 'SUPPORT_ANALYST' },
  'gina.chemavonian@airtm.io': { name: 'Gina Chemavonian', department: 'People', title: 'Head of People', role: 'LEADERSHIP' },
  'guido.alvarez@airtm.io': { name: 'Guido Francisco Martinez Alvarez', department: 'CommOps', title: 'Support Agent', role: 'SUPPORT_ANALYST' },
  'hannah.pinkarchevski@airtm.io': { name: 'Hannah Pinkarchevski', department: 'Legal', title: 'Head of Legal', role: 'LEADERSHIP' },
  'hekar.khani@airtm.io': { name: 'Hekar Khani', department: 'Tech', title: 'Staff Software Engineer (Infrastructure)', role: 'SUPPORT_ANALYST' },
  'heron.silva@airtm.io': { name: 'Heron Silva', department: 'Tech', title: 'Software Engineer (Backend)', role: 'SUPPORT_ANALYST' },
  'hong.dinh@airtm.io': { name: 'Hồng Ngọc Đinh', department: 'CommOps', title: 'Support Agent', role: 'SUPPORT_ANALYST' },
  'ivan.zabiello@airtm.io': { name: 'Ivan Zabiello', department: 'Finance', title: 'Head of Business Operations', role: 'LEADERSHIP' },
  'javier.mamani@airtm.io': { name: 'Javier Carlos Gutierrez Mamani', department: 'Tech', title: 'Senior Software Engineer (Frontend)', role: 'SUPPORT_ANALYST' },
  'jerlin.hernandez@airtm.io': { name: 'Jerlin Xiomari Siso Hernandez', department: 'CommOps', title: 'CommOps Lead', role: 'SUPPORT_ANALYST' },
  'jimena.poy@airtm.io': { name: 'Jimena Vanesa Poy', department: 'Compliance', title: 'Fraud Lead', role: 'FRAUD_INVESTIGATOR' },
  'jonathan.mejia@airtm.io': { name: 'Jonathan Ricardo Badillo Mejia', department: 'Tech', title: 'Senior Software Engineer (Backend)', role: 'SUPPORT_ANALYST' },
  'jorge.lomas@airtm.io': { name: 'Jorge Armando Diaz Lomas', department: 'Tech', title: 'Staff Software Engineer (Backend)', role: 'SUPPORT_ANALYST' },
  'jose.ulloque@airtm.io': { name: 'Jose Alejandro Angulo Ulloque', department: 'CommOps', title: 'Support Agent', role: 'SUPPORT_ANALYST' },
  'jose.crespo@airtm.io': { name: 'José Crespo', department: 'Compliance', title: 'Verifications Lead', role: 'KYC_ANALYST' },
  'jose.garcia@airtm.io': { name: 'Jose Francisco Salazar Garcia', department: 'Compliance', title: 'Fraud Analyst', role: 'FRAUD_INVESTIGATOR' },
  'jose.amorone@airtm.io': { name: 'Jose Luis Amorone', department: 'CommOps', title: 'Product Ops Analyst', role: 'SUPPORT_ANALYST' },
  'jose.lepe@airtm.io': { name: 'Jose Luis Curi Lepe', department: 'Finance', title: 'Head of FinOps and FP&L', role: 'LEADERSHIP' },
  'jose.diosa@airtm.io': { name: 'Jose Manuel Urrea Diosa', department: 'CommOps', title: 'CommOps Lead', role: 'SUPPORT_ANALYST' },
  'josue.rodriguez@airtm.io': { name: 'Josue Rodriguez', department: 'Tech', title: 'Software Engineer (Android)', role: 'SUPPORT_ANALYST' },
  'juan.cerqueira@airtm.io': { name: 'Juan Carlos Silva Cerqueira', department: 'Marketplace', title: 'Head of Marketplace & Partnerships', role: 'LEADERSHIP' },
  'juan.fernandez@airtm.io': { name: 'Juan Gabriel Paiva Fernández', department: 'Product', title: 'Senior UX Designer', role: 'SUPPORT_ANALYST' },
  'juan.estupinan@airtm.io': { name: 'Juan Pablo Cuellar Estupiñan', department: 'CommOps', title: 'Subject Matter Expert', role: 'SUPPORT_ANALYST' },
  'julian.hidalgo@airtm.io': { name: 'Julian David Villamizar Hidalgo', department: 'Growth & Mktg', title: 'Web Designer', role: 'SUPPORT_ANALYST' },
  'karina.verdugo@airtm.io': { name: 'Karina Gimena Verdugo', department: 'Compliance', title: 'Compliance 1st Level Senior Analyst', role: 'KYC_ANALYST' },
  'kyrie.hernandez@airtm.io': { name: 'Kyrie Martínez Hernandez', department: 'Tech', title: 'Tech Lead', role: 'SUPPORT_ANALYST' },
  'lasana.murray@airtm.io': { name: 'Lasana Murray', department: 'Tech', title: 'Software Engineer (Backend)', role: 'SUPPORT_ANALYST' },
  'laura.quijano@airtm.io': { name: 'Laura Beatriz Sanchez Quijano', department: 'Tech', title: 'Project Manager', role: 'SUPPORT_ANALYST' },
  'laura.seamon@airtm.io': { name: 'Laura Seamon', department: 'Legal', title: 'CLO', role: 'LEADERSHIP' },
  'luat.truong@airtm.io': { name: 'Luat Dong Truong', department: 'CommOps', title: 'Support Agent', role: 'SUPPORT_ANALYST' },
  'lucia.bustamante@airtm.io': { name: 'Lucia Bustamante', department: 'Product', title: 'Senior UX Designer', role: 'SUPPORT_ANALYST' },
  'lucia.caballero@airtm.io': { name: 'Lucia Cabeza Caballero', department: 'Compliance', title: 'KYB & KYV Junior Analyst', role: 'KYC_ANALYST' },
  'luciano.mosquera@airtm.io': { name: 'Luciano Martin Perez Mosquera', department: 'Product', title: 'Head of Product Strategy', role: 'LEADERSHIP' },
  'manuela.vilchez@airtm.io': { name: 'Manuela de Fátima Flores Vilchez', department: 'Tech', title: 'Software Engineer (Android)', role: 'SUPPORT_ANALYST' },
  'marcos.schramm@airtm.io': { name: 'Marcos Schramm', department: 'Compliance', title: 'Transaction Monitoring Analyst', role: 'TM_ANALYST' },
  'maria.olave@airtm.io': { name: 'Maria Fernanda Trujillo Olave', department: 'CommOps', title: 'Support Agent', role: 'SUPPORT_ANALYST' },
  'maria.fulleri@airtm.io': { name: 'María Gabriela Fulleri', department: 'Compliance', title: 'Compliance 1st Level Senior Analyst', role: 'KYC_ANALYST' },
  'maria.herbas@airtm.io': { name: 'María Lorena Osorio Herbas', department: 'CommOps', title: 'Support Agent', role: 'SUPPORT_ANALYST' },
  'maria.vidal@airtm.io': { name: 'Maria Luisa Lovaton Vidal', department: 'Tech', title: 'Senior Software Engineer (Frontend)', role: 'SUPPORT_ANALYST' },
  'maricarmen.chauta@airtm.io': { name: 'Maricarmen Quijano Chauta', department: 'Growth & Mktg', title: 'UX Designer', role: 'SUPPORT_ANALYST' },
  'marlin.bolivar@airtm.io': { name: 'Marlin Josefina Crespo Bolivar', department: 'CommOps', title: 'CommOps Lead', role: 'SUPPORT_ANALYST' },
  'mateo.proano@airtm.io': { name: 'Mateo Hervas Proaño', department: 'Tech', title: 'Tech Lead', role: 'SUPPORT_ANALYST' },
  'matthew.keen@airtm.io': { name: 'Matthew John Keen', department: 'Legal', title: 'Counsel', role: 'SUPPORT_ANALYST' },
  'max.borges@airtm.io': { name: 'Max Leandro Barbosa Borges', department: 'Tech', title: 'QA Engineer', role: 'SUPPORT_ANALYST' },
  'melanie.suckau@airtm.io': { name: 'Melanie Wer Suckau', department: 'Compliance', title: 'Transaction Monitoring Lead', role: 'TM_ANALYST' },
  'michelle.sabag@airtm.io': { name: 'Michelle Vargas Sabag', department: 'CommOps', title: 'Support Agent', role: 'SUPPORT_ANALYST' },
  'monica.camps@airtm.io': { name: 'Monica Camps', department: 'Compliance', title: 'KYB & KYV Lead', role: 'KYC_ANALYST' },
  'nathaniel.guillen@airtm.io': { name: 'Nathaniel Alejandro Calderon Guillen', department: 'Growth & Mktg', title: 'Junior Marketing Associate', role: 'SUPPORT_ANALYST' },
  'nicolas.briasco@airtm.io': { name: 'Nicolas Carlos Briasco', department: 'Growth & Mktg', title: 'Head of Product Marketing', role: 'LEADERSHIP' },
  'nohelia.villanueva@airtm.io': { name: 'Nohelia Patricia Cerritos Villanueva', department: 'Compliance', title: 'Senior Transaction Monitoring Analyst', role: 'TM_ANALYST' },
  'olaleye.aanuoluwapo@airtm.io': { name: 'Olaleye Adesola Aanuoluwapo', department: 'CommOps', title: 'Senior Support Agent', role: 'SUPPORT_ANALYST' },
  'omar.isea@airtm.io': { name: 'Omar Isea', department: 'Compliance', title: 'Head of Platform Safety', role: 'FRAUD_INVESTIGATOR' },
  'paola.hernandez@airtm.io': { name: 'Paola Hernandez', department: 'Compliance', title: 'Fraud Analyst', role: 'FRAUD_INVESTIGATOR' },
  'paula.suarez@airtm.io': { name: 'Paula Suarez', department: 'Compliance', title: 'Regional Compliance Officer', role: 'TM_ANALYST' },
  'pham.quynh@airtm.io': { name: 'Pham Thi Ngoc Quynh', department: 'CommOps', title: 'Subject Matter Expert', role: 'SUPPORT_ANALYST' },
  'rafael.duster@airtm.io': { name: 'Rafael Martins Duster', department: 'Tech', title: 'Senior Software Engineer (Backend)', role: 'SUPPORT_ANALYST' },
  'rainer.trochez@airtm.io': { name: 'Rainer Josue Bonilla Trochez', department: 'Tech', title: 'Software Engineer (Backend)', role: 'SUPPORT_ANALYST' },
  'renan.dias@airtm.io': { name: 'Renan Benatti Dias', department: 'Tech', title: 'Senior Software Engineer (iOS)', role: 'SUPPORT_ANALYST' },
  'ricardo.arevalo@airtm.io': { name: 'Ricardo Enrique Molina Arevalo', department: 'Compliance', title: 'Verification Analyst', role: 'KYC_ANALYST' },
  'ricardo.pitton@airtm.io': { name: 'Ricardo Hector Pitton', department: 'Growth & Mktg', title: 'Head of Community', role: 'LEADERSHIP' },
  'richard.ranalletta@airtm.io': { name: 'Richard Javier Lanz Ranalletta', department: 'Sales', title: 'Sr Onboarding consultant', role: 'SUPPORT_ANALYST' },
  'robson.silva@airtm.io': { name: 'Robson Fernando Da Silva', department: 'CommOps', title: 'Support Agent', role: 'SUPPORT_ANALYST' },
  'rodrigo.reyes@airtm.io': { name: 'Rodrigo Contreras Reyes', department: 'Tech', title: 'Tech Lead', role: 'SUPPORT_ANALYST' },
  'rodrigo.silva@airtm.io': { name: 'Rodrigo Pereira da Silva', department: 'Compliance', title: 'Transaction Monitoring Analyst', role: 'TM_ANALYST' },
  'rogelio.robles@airtm.io': { name: 'Rogelio Evenicer Valle Robles', department: 'Marketplace', title: 'Data Scientist', role: 'SUPPORT_ANALYST' },
  'roger.laureano@airtm.io': { name: 'Roger Gustavo Manenti Laureano', department: 'Product', title: 'Senior UX Researcher', role: 'SUPPORT_ANALYST' },
  'roger.moreno@airtm.io': { name: 'Roger Ventura Manzanares Moreno', department: 'CommOps', title: 'Support Agent', role: 'SUPPORT_ANALYST' },
  'ruben.galindo@airtm.io': { name: 'Ruben Galindo', department: 'CEO', title: 'CEO', role: 'LEADERSHIP' },
  'santiago.coates@airtm.io': { name: 'Santiago Coates', department: 'Growth & Mktg', title: 'Content Marketing Manager', role: 'SUPPORT_ANALYST' },
  'sarah.frese@airtm.io': { name: 'Sarah Frese', department: 'Growth & Mktg', title: 'CMO', role: 'LEADERSHIP' },
  'sergio.barajas@airtm.io': { name: 'Sergio Barajas', department: 'Operations', title: 'Head of Strategic Operations', role: 'LEADERSHIP' },
  'sergio.clem@airtm.io': { name: 'Sergio Luis Clem', department: 'Tech', title: 'Tech Lead', role: 'SUPPORT_ANALYST' },
  'shalav.gupta@airtm.io': { name: 'Shalav Gupta', department: 'Product', title: 'Head of Enterprise Product', role: 'LEADERSHIP' },
  'sneider.araque@airtm.io': { name: 'Sneider Andrés Sánchez Araque', department: 'Tech', title: 'Software Engineer (Frontend)', role: 'SUPPORT_ANALYST' },
  'tomas.dipieiro@airtm.io': { name: 'Tomas Di Pietro', department: 'Compliance', title: 'Verification Analyst', role: 'KYC_ANALYST' },
  'valentina.camacho@airtm.io': { name: 'Valentina Ortega Camacho', department: 'Compliance', title: 'Verification Analyst', role: 'KYC_ANALYST' },
  'vanina.villegas@airtm.io': { name: 'Vanina Villanueva Villegas', department: 'Compliance', title: 'Fraud Analyst', role: 'FRAUD_INVESTIGATOR' },
  'veronica.fernandez@airtm.io': { name: 'Veronica Cano Fernández', department: 'Finance', title: 'Accounting Lead', role: 'SUPPORT_ANALYST' },
  'vinicius.araujo@airtm.io': { name: 'Vinícius Da Silva Araujo', department: 'Tech', title: 'Software Engineer (Infrastructure)', role: 'SUPPORT_ANALYST' },
  'wemerson.silva@airtm.io': { name: 'Wemerson Silva', department: 'Tech', title: 'Senior Software Engineer (QA)', role: 'SUPPORT_ANALYST' },
  'zaid.khan@airtm.io': { name: 'Zaid Khan', department: 'Compliance', title: 'Head of Compliance', role: 'LEADERSHIP' },
  'zaira.fonseca@airtm.io': { name: 'Zaira Fonseca', department: 'Compliance', title: 'Compliance 1st level Analyst', role: 'KYC_ANALYST' },
  'zuleika.bennis@airtm.io': { name: 'Zuleika Bennis', department: 'CommOps', title: 'Subject Matter Expert', role: 'SUPPORT_ANALYST' }
};

// Role permissions mapping
const ROLE_PORTALS = {
  SUPPORT_ANALYST: ['support'],
  FRAUD_INVESTIGATOR: ['fraud', 'support'],
  KYC_ANALYST: ['kyc', 'support'],
  TM_ANALYST: ['tm', 'support'],
  LEADERSHIP: ['support', 'fraud', 'kyc', 'tm', 'audit']
};

module.exports = { EMPLOYEES, ROLE_PORTALS };
