// ============================================================
// VIGÍA Compliance Portal — Employee Whitelist (Updated 2026-05-19)
// Source: AIRTM_EMPLOYEE_MASTER_FILE.csv (135 employees)
// Authorized by: Zaid Khan (U087TL6CGNM)
// ============================================================

const EMPLOYEES = {
  'aadarsh@airtm.io': { name: 'Aadarsh Kumar Singh', department: 'Marketplace', title: 'Head of Analytics', role: 'LEADERSHIP' },
  'aashi@airtm.io': { name: 'Aashi Choudhary', department: 'Compliance', title: 'AML Junior Analyst', role: 'KYC_ANALYST' },
  'abraham@airtm.io': { name: 'Abraham Martínez López', department: 'Marketplace', title: 'Data Scientist', role: 'SUPPORT_ANALYST' },
  'adalberto@airtm.io': { name: 'Adalberto Benitez Zapata', department: 'Growth & Mktg', title: 'Sr Growth Lead', role: 'SUPPORT_ANALYST' },
  'adam@airtm.io': { name: 'Adam Baer', department: 'Finance', title: 'VP Financial Controller', role: 'LEADERSHIP' },
  'aimee@airtm.io': { name: 'Aimee Vanessa Villarroel Barajas', department: 'Compliance', title: 'Compliance 1st level Analyst', role: 'KYC_ANALYST' },
  'alanlucian@airtm.io': { name: 'Alan Lucian Milanes Tormente', department: 'Tech', title: 'Senior Software Engineer (Backend)', role: 'SUPPORT_ANALYST' },
  'alberto@airtm.io': { name: 'Alberto Pickering Dubovoy', department: 'Tech', title: 'Tech Lead', role: 'SUPPORT_ANALYST' },
  'aldo@airtm.io': { name: 'Aldo Funes Minutti', department: 'Tech', title: 'VP of Engineering', role: 'LEADERSHIP' },
  'mishell@airtm.io': { name: 'Alexis Mishell Rodriguez Vicente', department: 'CommOps', title: 'Subject Matter Expert', role: 'SUPPORT_ANALYST' },
  'alia@airtm.io': { name: 'Ali Areski', department: 'Compliance', title: 'Governance and Controls Analyst', role: 'KYC_ANALYST' },
  'allansilva@airtm.io': { name: 'Allan Raul Silva', department: 'Product', title: 'Senior Product Manager', role: 'SUPPORT_ANALYST' },
  'anahita@airtm.io': { name: 'Anahita Arora', department: 'Finance', title: 'CFO', role: 'LEADERSHIP' },
  'anaisabel@airtm.io': { name: 'Ana Isabel Villarroel Marquez', department: 'Compliance', title: 'Verification Analyst', role: 'KYC_ANALYST' },
  'andresalberto@airtm.io': { name: 'Andres Alberto Huerta Monroy', department: 'Compliance', title: 'Verification Analyst', role: 'KYC_ANALYST' },
  'angy@airtm.io': { name: 'Angy Mileidy Duarte de Tovar', department: 'CommOps', title: 'CommOps Manager', role: 'SUPPORT_ANALYST' },
  'anny@airtm.io': { name: 'Anny Marleidy Duarte Castro', department: 'Growth & Mktg', title: 'Social Media Support & Community Voice', role: 'SUPPORT_ANALYST' },
  'anyelina@airtm.io': { name: 'Anyelina Estrella Martinez', department: 'Compliance', title: 'Compliance 1st level Analyst', role: 'KYC_ANALYST' },
  'arshi@airtm.io': { name: 'Arshi Singh', department: 'Product', title: 'CPO', role: 'LEADERSHIP' },
  'arturop@airtm.io': { name: 'Arturo Ernesto Perdomo', department: 'Compliance', title: 'Verification Analyst', role: 'KYC_ANALYST' },
  'ashvini@airtm.io': { name: 'Ashvini Weragoda', department: 'CommOps', title: 'Support Agent', role: 'SUPPORT_ANALYST' },
  'bruno@airtm.io': { name: 'Bruno Dos Santos Picciafuoco', department: 'Tech', title: 'Senior Software Engineer (Backend)', role: 'SUPPORT_ANALYST' },
  'bryan@airtm.io': { name: 'Bryan Andres Medina Florez', department: 'CommOps', title: 'Support Agent', role: 'SUPPORT_ANALYST' },
  'camila@airtm.io': { name: 'Camila María Mercado Arce', department: 'CommOps', title: 'Support Agent', role: 'SUPPORT_ANALYST' },
  'camilo@airtm.io': { name: 'Camilo Esteban Cardozo Chaparro', department: 'People', title: 'Recruiter', role: 'SUPPORT_ANALYST' },
  'carlosh@airtm.io': { name: 'Carlos Habib De Lamadrid Miranda', department: 'Legal', title: 'Counsel', role: 'SUPPORT_ANALYST' },
  'carloshernandez@airtm.io': { name: 'Carlos Roberto Hernández Flores', department: 'CommOps', title: 'Support Agent', role: 'SUPPORT_ANALYST' },
  'ariel@airtm.io': { name: 'Christian Ariel Colla', department: 'Finance', title: 'Senior Accountant', role: 'SUPPORT_ANALYST' },
  'christian@airtm.io': { name: 'Christian Esteban Canahuire Cabello', department: 'Tech', title: 'Senior Software Engineer (Android)', role: 'SUPPORT_ANALYST' },
  'cicero@airtm.io': { name: 'Cicero Augusto De Souza Camargo', department: 'Tech', title: 'Senior Software Engineer (iOS)', role: 'SUPPORT_ANALYST' },
  'erika@airtm.io': { name: 'Claudia Erika Martinez Merino', department: 'Compliance', title: 'KYC Global Manager', role: 'KYC_ANALYST' },
  'cristina@airtm.io': { name: 'Cristina Rodriguez Jordan', department: 'Growth & Mktg', title: 'Marketing Operations Coordinator', role: 'SUPPORT_ANALYST' },
  'cristobal@airtm.io': { name: 'Cristobal Galguera Ortega', department: 'Product', title: 'Senior Product Manager', role: 'SUPPORT_ANALYST' },
  'hoangvu@airtm.io': { name: 'Dang Hoang Vu Tran', department: 'CommOps', title: 'Support Agent', role: 'SUPPORT_ANALYST' },
  'danielaperez@airtm.io': { name: 'Daniela Sarai Perez Carvajal', department: 'Growth & Mktg', title: 'Growth Marketing Associate Analyst', role: 'SUPPORT_ANALYST' },
  'danielbenjamin@airtm.io': { name: 'Daniel Benjamin Almaraz Marroquín', department: 'Compliance', title: '1st Level Compliance Lead', role: 'KYC_ANALYST' },
  'danielenrique@airtm.io': { name: 'Daniel Enrique De La Cruz Villegas', department: 'Marketplace', title: 'Marketplace Ops Associate', role: 'SUPPORT_ANALYST' },
  'danielq@airtm.io': { name: 'Daniel Quintero', department: 'Finance', title: 'Senior Accountant', role: 'SUPPORT_ANALYST' },
  'diegopels@airtm.io': { name: 'Diego Alan Pels', department: 'Sales', title: 'Account Manager', role: 'SUPPORT_ANALYST' },
  'edgarh@airtm.io': { name: 'Edgar Hirama', department: 'Tech', title: 'Senior Software Engineer (iOS)', role: 'SUPPORT_ANALYST' },
  'edoe@airtm.io': { name: 'Edoe Jose Chourio Rodriguez', department: 'CommOps', title: 'Senior Support Agent', role: 'SUPPORT_ANALYST' },
  'eduardon@airtm.io': { name: 'Eduardo Jose Nieto Perez', department: 'Compliance', title: 'Fraud Analyst', role: 'FRAUD_INVESTIGATOR' },
  'marianodeudaeta@airtm.io': { name: 'Eduardo Mariano de Udaeta Ramírez', department: 'CommOps', title: 'Support Agent', role: 'SUPPORT_ANALYST' },
  'eleana@airtm.io': { name: 'Eleana Judith Chourio Rodriguez', department: 'Compliance', title: 'Compliance 1st level Analyst', role: 'KYC_ANALYST' },
  'elias@airtm.io': { name: 'Elías David Duarte', department: 'Tech', title: 'Software Engineer (Backend)', role: 'SUPPORT_ANALYST' },
  'enrique@airtm.io': { name: 'Enrique Jose Santeliz Lopez', department: 'Tech', title: 'Senior Software Engineer (Backend)', role: 'SUPPORT_ANALYST' },
  'erick@airtm.io': { name: 'Erick Cedillo Romero', department: 'Tech', title: 'Software Engineer (Frontend)', role: 'SUPPORT_ANALYST' },
  'estefania@airtm.io': { name: 'Estefania Celeste Baleiron fucci', department: 'Compliance', title: 'KYC Analyst', role: 'KYC_ANALYST' },
  'fabioalcocer@airtm.io': { name: 'Fabio Marcelo Alcocer Sejas', department: 'CommOps', title: 'Support Agent', role: 'SUPPORT_ANALYST' },
  'florenciat@airtm.io': { name: 'Florencia Agustina Tisocco', department: 'Growth & Mktg', title: 'Senior Engagement Analyst', role: 'SUPPORT_ANALYST' },
  'florencia@airtm.io': { name: 'Florencia Carnelutto', department: 'Finance', title: 'Data Scientist', role: 'SUPPORT_ANALYST' },
  'franciscoelias@airtm.io': { name: 'Francisco Elias Valdez', department: 'Product', title: 'Senior UX Designer', role: 'SUPPORT_ANALYST' },
  'gabriel@airtm.io': { name: 'Gabriel Guilherme de Oliveira Silva', department: 'CommOps', title: 'Support Agent', role: 'SUPPORT_ANALYST' },
  'gina@airtm.io': { name: 'Gina Chemavonian', department: 'People', title: 'Head of People', role: 'LEADERSHIP' },
  'guido@airtm.io': { name: 'Guido Francisco Martinez Alvarez', department: 'CommOps', title: 'Support Agent', role: 'SUPPORT_ANALYST' },
  'hannah@airtm.io': { name: 'Hannah Pinkarchevski', department: 'Legal', title: 'Head of Legal', role: 'LEADERSHIP' },
  'hekar@airtm.io': { name: 'Hekar Khani', department: 'Tech', title: 'Staff Software Engineer (Infrastructure)', role: 'SUPPORT_ANALYST' },
  'heron@airtm.io': { name: 'Heron Silva', department: 'Tech', title: 'Software Engineer (Backend)', role: 'SUPPORT_ANALYST' },
  'dinh@airtm.io': { name: 'Hồng Ngọc Đinh', department: 'CommOps', title: 'Support Agent', role: 'SUPPORT_ANALYST' },
  'ivanz@airtm.io': { name: 'Ivan Zabiello', department: 'Finance', title: 'Head of Business Operations', role: 'LEADERSHIP' },
  'javierg@airtm.io': { name: 'Javier Carlos Gutierrez Mamani', department: 'Tech', title: 'Senior Software Engineer (Frontend)', role: 'SUPPORT_ANALYST' },
  'jerlin@airtm.io': { name: 'Jerlin Xiomari Siso Hernandez', department: 'CommOps', title: 'CommOps Lead', role: 'SUPPORT_ANALYST' },
  'jimena@airtm.io': { name: 'Jimena Vanesa Poy', department: 'Compliance', title: 'Fraud Lead', role: 'FRAUD_INVESTIGATOR' },
  'jonathanb@airtm.io': { name: 'Jonathan Ricardo Badillo Mejia', department: 'Tech', title: 'Senior Software Engineer (Backend)', role: 'SUPPORT_ANALYST' },
  'jorged@airtm.io': { name: 'Jorge Armando Diaz Lomas', department: 'Tech', title: 'Staff Software Engineer (Backend)', role: 'SUPPORT_ANALYST' },
  'joseulloque@airtm.io': { name: 'Jose Alejandro Angulo Ulloque', department: 'CommOps', title: 'Support Agent', role: 'SUPPORT_ANALYST' },
  'josecr@airtm.io': { name: 'José Crespo', department: 'Compliance', title: 'Verifications Lead', role: 'KYC_ANALYST' },
  'franciscos@airtm.io': { name: 'Jose Francisco Salazar Garcia', department: 'Compliance', title: 'Fraud Analyst', role: 'FRAUD_INVESTIGATOR' },
  'josea@airtm.io': { name: 'Jose Luis Amorone', department: 'CommOps', title: 'Product Ops Analyst', role: 'SUPPORT_ANALYST' },
  'josec@airtm.io': { name: 'Jose Luis Curi Lepe', department: 'Finance', title: 'Head of FinOps and FP&L', role: 'LEADERSHIP' },
  'josemanuel@airtm.io': { name: 'Jose Manuel Urrea Diosa', department: 'CommOps', title: 'CommOps Lead', role: 'SUPPORT_ANALYST' },
  'josue@airtm.io': { name: 'Josue Rodriguez', department: 'Tech', title: 'Software Engineer (Android)', role: 'SUPPORT_ANALYST' },
  'juansilva@airtm.io': { name: 'Juan Carlos Silva Cerqueira', department: 'Marketplace', title: 'Head of Marketplace & Partnerships', role: 'LEADERSHIP' },
  'juangabriel@airtm.io': { name: 'Juan Gabriel Paiva Fernández', department: 'Product', title: 'Senior UX Designer', role: 'SUPPORT_ANALYST' },
  'juancuellar@airtm.io': { name: 'Juan Pablo Cuellar Estupiñan', department: 'CommOps', title: 'Subject Matter Expert', role: 'SUPPORT_ANALYST' },
  'julian@airtm.io': { name: 'Julian David Villamizar Hidalgo', department: 'Growth & Mktg', title: 'Web Designer', role: 'SUPPORT_ANALYST' },
  'karinav@airtm.io': { name: 'Karina Gimena Verdugo', department: 'Compliance', title: 'Compliance 1st Level Senior Analyst', role: 'KYC_ANALYST' },
  'master@airtm.io': { name: 'Kyrie Martínez Hernandez', department: 'Tech', title: 'Tech Lead', role: 'SUPPORT_ANALYST' },
  'lasana@airtm.io': { name: 'Lasana Murray', department: 'Tech', title: 'Software Engineer (Backend)', role: 'SUPPORT_ANALYST' },
  'laura@airtm.io': { name: 'Laura Beatriz Sanchez Quijano', department: 'Tech', title: 'Poject Manager', role: 'SUPPORT_ANALYST' },
  'lauras@airtm.io': { name: 'Laura Seamon', department: 'Legal', title: 'CLO', role: 'LEADERSHIP' },
  'luat@airtm.io': { name: 'Luat Dong Truong', department: 'CommOps', title: 'Support Agent', role: 'SUPPORT_ANALYST' },
  'luciabustamante@airtm.io': { name: 'Lucia Bustamante', department: 'Product', title: 'Senior UX Designer', role: 'SUPPORT_ANALYST' },
  'lucia@airtm.io': { name: 'Lucia Cabeza Caballero', department: 'Compliance', title: 'KYB & KYV Junior Analyst', role: 'KYC_ANALYST' },
  'luciano@airtm.io': { name: 'Luciano Martin Perez Mosquera', department: 'Product', title: 'Head of Product Strategy', role: 'LEADERSHIP' },
  'manuelaflores@airtm.io': { name: 'Manuela de Fátima Flores Vilchez', department: 'Tech', title: 'Software Engineer (Android)', role: 'SUPPORT_ANALYST' },
  'marcos@airtm.io': { name: 'Marcos Schramm', department: 'Compliance', title: 'Transaction Monitoring Analyst', role: 'TM_ANALYST' },
  'mariafernanda@airtm.io': { name: 'Maria Fernanda Trujillo Olave', department: 'CommOps', title: 'Support Agent', role: 'SUPPORT_ANALYST' },
  'mariagabriela@airtm.io': { name: 'María Gabriela Fulleri', department: 'Compliance', title: 'Compliance 1st Level Senior Analyst', role: 'KYC_ANALYST' },
  'marialorena@airtm.io': { name: 'María Lorena Osorio Herbas', department: 'CommOps', title: 'Support Agent', role: 'SUPPORT_ANALYST' },
  'marialuisa@airtm.io': { name: 'Maria Luisa Lovaton Vidal', department: 'Tech', title: 'Senior Software Engineer (Frontend)', role: 'SUPPORT_ANALYST' },
  'maricarmen@airtm.io': { name: 'Maricarmen Quijano Chauta', department: 'Growth & Mktg', title: 'UX Designer', role: 'SUPPORT_ANALYST' },
  'marlin@airtm.io': { name: 'Marlin Josefina Crespo Bolivar', department: 'CommOps', title: 'CommOps Lead', role: 'SUPPORT_ANALYST' },
  'mateo@airtm.io': { name: 'Mateo Hervas Proaño', department: 'Tech', title: 'Tech Lead', role: 'SUPPORT_ANALYST' },
  'matthew@airtm.io': { name: 'Matthew John Keen', department: 'Legal', title: 'Counsel', role: 'SUPPORT_ANALYST' },
  'maxleandro@airtm.io': { name: 'Max Leandro Barbosa Borges', department: 'Tech', title: 'QA Engineer', role: 'SUPPORT_ANALYST' },
  'melanie@airtm.io': { name: 'Melanie Wer Suckau', department: 'Compliance', title: 'Transaction Monitoring Lead', role: 'TM_ANALYST' },
  'michelle@airtm.io': { name: 'Michelle Vargas Sabag', department: 'CommOps', title: 'Support Agent', role: 'SUPPORT_ANALYST' },
  'monicacamps@airtm.io': { name: 'Monica Camps', department: 'Compliance', title: 'KYB & KYV Lead', role: 'KYC_ANALYST' },
  'nathaniel@airtm.io': { name: 'Nathaniel Alejandro Calderon Guillen', department: 'Growth & Mktg', title: 'Junior Marketing Associate', role: 'SUPPORT_ANALYST' },
  'nico@airtm.io': { name: 'Nicolas Carlos Briasco', department: 'Growth & Mktg', title: 'Head of Product Marketing', role: 'LEADERSHIP' },
  'nohelia@airtm.io': { name: 'Nohelia Patricia Cerritos Villanueva', department: 'Compliance', title: 'Senior Transaction Monitoring Analyst', role: 'TM_ANALYST' },
  'adesola@airtm.io': { name: 'Olaleye Adesola Aanuoluwapo', department: 'CommOps', title: 'Senior Support Agent', role: 'SUPPORT_ANALYST' },
  'omar@airtm.io': { name: 'Omar Isea', department: 'Compliance', title: 'Head of Platform Safety', role: 'LEADERSHIP' },
  'paolah@airtm.io': { name: 'Paola Hernandez', department: 'Compliance', title: 'Fraud Analyst', role: 'FRAUD_INVESTIGATOR' },
  'paula@airtm.io': { name: 'Paula Suarez', department: 'Compliance', title: 'Regional Compliance Officer', role: 'KYC_ANALYST' },
  'quynh@airtm.io': { name: 'Pham Thi Ngoc Quynh', department: 'CommOps', title: 'Subject Matter Expert', role: 'SUPPORT_ANALYST' },
  'rafael@airtm.io': { name: 'Rafael Martins Duster', department: 'Tech', title: 'Senior Software Engineer (Backend)', role: 'SUPPORT_ANALYST' },
  'rainer@airtm.io': { name: 'Rainer Josue Bonilla Trochez', department: 'Tech', title: 'Software Engineer (Backend)', role: 'SUPPORT_ANALYST' },
  'renan@airtm.io': { name: 'Renan Benatti Dias', department: 'Tech', title: 'Senior Software Engineer (iOS)', role: 'SUPPORT_ANALYST' },
  'ricardomolina@airtm.io': { name: 'Ricardo Enrique Molina Arevalo', department: 'Compliance', title: 'Verification Analyst', role: 'KYC_ANALYST' },
  'ricardo@airtm.io': { name: 'Ricardo Hector Pitton', department: 'Growth & Mktg', title: 'Head of Community', role: 'LEADERSHIP' },
  'richard@airtm.io': { name: 'Richard Javier Lanz Ranalletta', department: 'Sales', title: 'Sr Onboarding consultant', role: 'SUPPORT_ANALYST' },
  'robson@airtm.io': { name: 'Robson Fernando Da Silva', department: 'CommOps', title: 'Support Agent', role: 'SUPPORT_ANALYST' },
  'rodrigocr@airtm.io': { name: 'Rodrigo Contreras Reyes', department: 'Tech', title: 'Tech Lead', role: 'SUPPORT_ANALYST' },
  'rodrigopereira@airtm.io': { name: 'Rodrigo Pereira da Silva', department: 'Compliance', title: 'Transaction Monitoring Analyst', role: 'TM_ANALYST' },
  'rogelio@airtm.io': { name: 'Rogelio Evenicer Valle Robles', department: 'Marketplace', title: 'Data Scientist', role: 'SUPPORT_ANALYST' },
  'rogerlaureano@airtm.io': { name: 'Roger Gustavo Manenti Laureano', department: 'Product', title: 'Senior UX Researcher', role: 'SUPPORT_ANALYST' },
  'roger@airtm.io': { name: 'Roger Ventura Manzanares Moreno', department: 'CommOps', title: 'Support Agent', role: 'SUPPORT_ANALYST' },
  'ruben@airtm.io': { name: 'Ruben Galindo', department: 'CEO', title: 'CEO', role: 'LEADERSHIP' },
  'santiagoc@airtm.io': { name: 'Santiago Coates', department: 'Growth & Mktg', title: 'Content Marketing Manager', role: 'SUPPORT_ANALYST' },
  'sarah@airtm.io': { name: 'Sarah Frese', department: 'Growth & Mktg', title: 'CMO', role: 'LEADERSHIP' },
  'sergio@airtm.io': { name: 'Sergio Barajas', department: 'Operations', title: 'Head of Strategic Operations', role: 'LEADERSHIP' },
  'sergiocl@airtm.io': { name: 'Sergio Luis Clem', department: 'Tech', title: 'Tech Lead', role: 'SUPPORT_ANALYST' },
  'shalav@airtm.io': { name: 'Shalav Gupta', department: 'Product', title: 'Head of Enterprise Product', role: 'LEADERSHIP' },
  'sneider@airtm.io': { name: 'Sneider Andrés Sánchez Araque', department: 'Tech', title: 'Software Engineer (Frontend)', role: 'SUPPORT_ANALYST' },
  'tomasd@airtm.io': { name: 'Tomas Di Pietro', department: 'Compliance', title: 'Verification Analyst', role: 'KYC_ANALYST' },
  'valentina@airtm.io': { name: 'Valentina Ortega Camacho', department: 'Compliance', title: 'Verification Analyst', role: 'KYC_ANALYST' },
  'vanina@airtm.io': { name: 'Vanina Villanueva Villegas', department: 'Compliance', title: 'Fraud Analyst', role: 'FRAUD_INVESTIGATOR' },
  'veronica@airtm.io': { name: 'Veronica Cano Fernández', department: 'Finance', title: 'Accounting Lead', role: 'SUPPORT_ANALYST' },
  'vinicius@airtm.io': { name: 'Vinícius Da Silva Araujo', department: 'Tech', title: 'Software Engineer (Infrastructure)', role: 'SUPPORT_ANALYST' },
  'wemerson@airtm.io': { name: 'Wemerson Silva', department: 'Tech', title: 'Senior Software Engineer (QA)', role: 'SUPPORT_ANALYST' },
  'zaid@airtm.io': { name: 'Zaid Khan', department: 'Compliance', title: 'Head of Compliance', role: 'LEADERSHIP' },
  'zaira@airtm.io': { name: 'Zaira Fonseca', department: 'Compliance', title: 'Compliance 1st level Analyst', role: 'KYC_ANALYST' },
  'zuleika@airtm.io': { name: 'Zuleika Bennis', department: 'CommOps', title: 'Subject Matter Expert', role: 'SUPPORT_ANALYST' },
};

const ROLE_PORTALS = {
  'LEADERSHIP': ['support', 'fraud', 'kyc', 'tm', 'leadership', 'dashboard'],
  'FRAUD_INVESTIGATOR': ['fraud', 'dashboard'],
  'KYC_ANALYST': ['kyc', 'dashboard'],
  'TM_ANALYST': ['tm', 'dashboard'],
  'SUPPORT_ANALYST': ['support'],
};

module.exports = { EMPLOYEES, ROLE_PORTALS };